name: flutter_local_auth_invisible
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader and Touch ID with no visible dialog on Android.
homepage: https://github.com/priezz/flutter_local_auth_invisible
version: 0.4.1+2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  intl: ">=0.15.1 <0.17.0"
  platform: ^3.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
